---
# configuration tasks file for redis

- name: Configure redis settings
  template:
    src: redis.conf.j2
    dest: "{{ redis_conf_file }}"
    owner: root
    group: "{{ redis_group }}"
    mode: 0640
  notify:
    restart redis

# TODO: Set the following?
#       sysctl -w vm.overcommit_memory=1
#       sysctl -w net.core.somaxconn=512
#       echo never > /sys/kernel/mm/transparent_hugepage/enabled
