---
# firewall-specific tasks for redis

- name: Open firewalld ports for Redis
  firewalld:
    port: "{{ redis_port }}/tcp"
    permanent: true
    state: enabled
    immediate: yes
  when:
    (use_firewalld is defined and use_firewalld)

- name: Open ufw ports for ElasticSearch
  ufw:
    port: "{{ redis_port }}"
    proto: tcp
    direction: in
    policy: allow
  when:
    (use_ufw is defined and use_ufw)
