---
# tasks file for redis

- include: debian.yml
  when:
    ansible_os_family == "Debian"
- include: redhat.yml
  when:
    ansible_os_family == "RedHat"

- include: config.yml
- include: service.yml
